[package]
name = "ci"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/delan/servo-ci"

[dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
