name: Main
on:
  push:
  pull_request:

jobs:
  main:
    name: Check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all --check
      - run: cargo clippy --workspace -- --deny warnings
      - run: cargo test --workspace
